### ISSUE TITLE
Gamepath with spaces not supported

### ISSUE THREAD

**Issue by Mindtwista** [nzgamer41/SegaToolsTP#2]
**Describe the bug**
The game runs only in an path without spaces. The original Segatools support gamepath with spaces

**Desktop (please complete the following information):**
 - OS: Windows 10 1803
 - TeknoParrotUI version 1.0.0.306

**Comment by nzgamer41** [comment]
@Mindtwista can you test and see whether the new TP update fixes your issue? It has for others but just want to make sure it does for you before i close the issue.

**Comment by Mindtwista** [comment]
Hi,
it works now.
Thank you
Greetings from Austria

Alex Cheer <notifications@github.com> schrieb am Fr. 10. Apr. 2020 um 15:32:
