### ISSUE TITLE
Error 8114

### ISSUE THREAD

**Issue by GtrevizeG** [nzgamer41/SegaToolsTP#3]
when launching the game via TP. the game boots correctly but after the first logo screen, I have a black screen with a 8114 network error

**Comment by nzgamer41** [comment]
Do you have node.js installed? Also have you set the NetworkAdapterIP correctly in the Game Settings? Error 8114 is a AIME error, "8114 - ALL.Net System Error(RTC)， Please make sure miniME is opened or check IP in segatools"

**Comment by GtrevizeG** [comment]
hello, node.js installed. here is my setup on TP 
![Clipboard-4](https://user-images.githubusercontent.com/63284216/78788148-b0c09100-79ab-11ea-8805-6ef1f1ba88fa.png)

and my segatool.ini. From what I have understoood this ini is updated on the fly by TP according to the TP setup when the game is launched ? please let me know if your need any log.

**Comment by GtrevizeG** [comment]
[vfs]
amfs=M:\Hyperspin\Roms\TeknoParrot\Teknoparrot\IDZ\SDDF_1.31.00\amfs
appdata=C:\Users\Gtrevize\AppData\Roaming\TeknoParrot\IDZ\

[dns]
default=0.0.0.0

[ds]
region=4

[netenv]
enable=1

[keychip]
subnet=0.0.0.0

[gpio]
dipsw1=1

[io3]
mode=tp
pos_shifter=1
autoNeutral=1
singleStickSteering=1
restrict=97

[dinput]
deviceName=
shifterName=
brakeAxis=RZ
accelAxis=Y
start=3
viewChg=10
shiftDn=1
shiftUp=2
gear1=1
gear2=2
gear3=3
gear4=4
gear5=5
gear6=6
reverseAccelAxis=0
reverseBrakeAxis=0

**Comment by GtrevizeG** [comment]
Microsoft Windows [version 10.0.18363.720]
(c) 2019 Microsoft Corporation. Tous droits réservés.

M:\Hyperspin\Emulators\TeknoParrot\SegaTools\minime>start.bat
--- Begin idz_pre_startup ---
Vfs: WARNING: OPTION path not specified in INI file
---  End  idz_pre_startup ---
internal/modules/cjs/loader.js:797
    throw err;
    ^

Error: Cannot find module 'M:\Hyperspin\Emulators\TeknoParrot\SegaTools\minime\bin\index.js'
[90m    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:794:15)[39m
[90m    at Function.Module._load (internal/modules/cjs/loader.js:687:27)[39m
[90m    at Function.Module.runMain (internal/modules/cjs/loader.js:1025:10)[39m
[90m    at internal/main/run_main_module.js:17:11[39m {
  code: [32m'MODULE_NOT_FOUND'[39m,
  requireStack: []
}
amdaemonExe Ver.2425 Build:Mar 29 2018 17:23:39

SetupAPI: Interface {741b5fca-...} -> Device node $sram
SRAM: Open device
SRAM: Get geometry
SetupAPI: Interface {b7970f0c-...} -> Device node $eeprom
EEPROM: Open device
EEPROM: Get geometry
SetupAPI: Interface {279a9f67-...} -> Device node $ds
DS: Open device
DS: Get geometry
DS: Setup IOCTL
SetupAPI: Interface {e9a26688-...} -> Device node $gpio
GPIO: Open device
GPIO: Describe GPIO ports
Process state: setup Game Mode
Security: Opened handle
DS: Read sector 00000000
Security: nusec_ioctl_get_nvram_geometry
Security: nusec_ioctl_get_nearfull
Hwmon: Opened device
AmVideo: amDllVideoOpen)
AmVideo: amDllVideoSetResolution
AmVideo: amDllVideoClose)
Netenv: GetAdaptersInfo: Virtualized LAN configuration:
Netenv: Interface IP :     0.  0.  0. 11
Netenv: Router IP    :     0.  0.  0.254
Netenv: MAC Address  : 01:02:03:04:05:06
Netenv: GetAdaptersInfo: Virtualized LAN configuration:
Netenv: Interface IP :     0.  0.  0. 11
Netenv: Router IP    :     0.  0.  0.254
Netenv: MAC Address  : 01:02:03:04:05:06
Netenv: GetAdaptersInfo: Virtualized LAN configuration:
Netenv: Interface IP :     0.  0.  0. 11
Netenv: Router IP    :     0.  0.  0.254
Netenv: MAC Address  : 01:02:03:04:05:06
SetupAPI: Interface {db6bbb45-...} -> Device node $jvs
JVS Port: Open device
JVS I/O: Starting Initial D Zero backend DLL
TeknoParrot SegaTools Support by nzgamer41
Individual Gear Shifter is enabled!
Using TeknoParrot Input Support
JVS Port: Port startup (?)
EEPROM: Read off 1f0 len 30
JVS I/O: Reset (param d9)
EEPROM: Read off 90 len b0
EEPROM: Read off 40 len 50
Error 0
NFC Assembly: Starting backend DLL
NFC 00: Reset
JVS I/O: Reset (param d9)
JVS Port: Sense line 2.5 V (address unassigned)
JVS I/O: Assign addr 01 sense 0
JVS Port: Sense line 0.0 V (address assigned)
JVS I/O: Get features
JVS I/O: Get command format version
JVS I/O: Get JVS version
JVS I/O: Get communication version
JVS I/O: Read ID
Netenv: GetBestRoute ip4 0 -> ip4 0
Process state: Advertise
Clock: Returning JST timezone
Security: nusec_ioctl_get_billing_pubkey
>>> 00000001408387C1:0/1024
<<< 00000001408387C1:162/1024
Security: nusec_ioctl_get_play_limit
Netenv: GetBestRoute ip4 0 -> ip4 b
Netenv: GetBestRoute ip4 0 -> ip4 b
Security: nusec_ioctl_get_nearfull
start LAN install - server.
Netenv: Virtualized ICMP Ping to ip4 fe
Security: nusec_ioctl_get_play_count
Netenv: Virtualized ICMP Ping to ip4 fe
Netenv: Virtualized ICMP Ping to ip4 fe
Security: nusec_ioctl_put_trace_log_data
    00000000: 01 14 04 08 0d 15 36 50 6f 77 65 72 20 6f 6e 20 ......6Power on
    00000010: 41 36 39 45 30 31 41 38 38 38 38 20 53 44 44 46 A69E01A8888 SDDF
    00000020: 20 31 2e 33 31 20 20 20 41 36 39 45 01 41 88 88  1.31   A69E.A..
    00000030: 18 05 00 00 00 00 00 00 00 00 00 00             ............

    H: 1 T: 0
Security: nusec_ioctl_put_trace_log_data
    00000000: 02 14 04 08 0d 15 36 00 00 00 01 01 00 01 01 01 ......6.........
    00000010: 01 02 03 04 05 06 18 05 41 36 39 45 01 41 88 88 ........A69E.A..
    00000020: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 ................
    00000030: 00 00 00 00 00 00 00 00 00 00 00 00             ............

    H: 2 T: 0
EEPROM: Read off 1000 len 80
Security: nusec_ioctl_get_nvram_available: used=2 avail=7152
Error 8114
start NET deliver.
App Image    - Download Status: 200
Option Image - Download Status: 200
--- Begin idz_pre_startup ---
Vfs: WARNING: OPTION path not specified in INI file
---  End  idz_pre_startup ---
Clock: Returning JST timezone
Netenv: GetAdaptersInfo: Virtualized LAN configuration:
Netenv: Interface IP :     0.  0.  0. 11
Netenv: Router IP    :     0.  0.  0.254
Netenv: MAC Address  : 01:02:03:04:05:06
ZInput: Blocking built-in DirectInput support
ZInput: hook_CreateDevice
ZInput: hook_SetDataFormat
ZInput: hook_SetCooperativeLevel
ZInput: hook_CreateDevice
ZInput: hook_SetDataFormat
ZInput: hook_SetCooperativeLevel
ZInput: hook_EnumDevices
The Direct3D device has a non-zero reference count, meaning some objects were not released.

**Comment by GtrevizeG** [comment]
reinstalling segatool from TP (deleting the folder) fixed it. Thank you !
