### ISSUE TITLE
Game wont open

### ISSUE THREAD

**Issue by andressj8** [nzgamer41/SegaToolsTP#4]
**Describe the bug**
The game just doesnt open, made all the steps, it seems that it works but it just wont open
it describes error 
Code=4104 not foundError 4104
Edit: For clarificacion, i watched nzgamer21 youtube tutorial, and the cmd window looks fine except that the direct3d window doesnt pops up, when i launch the game , my screen blink, like it tried to go fullscreen, and then goes back and theres no direct3d window opened up.

**To Reproduce**
Changed the hex in amdaemon.exe
installed the dependencies on minime
changed ip on teknoparrotui after updating it
launched the game

**Expected behavior**
to Open,lol.

**Screenshots**
![image](https://user-images.githubusercontent.com/55869634/78876163-ebaedd00-7a1c-11ea-87dd-0b22b9cb3854.png)
![image](https://user-images.githubusercontent.com/55869634/78876206-fc5f5300-7a1c-11ea-8c50-943566c315e9.png)
![image](https://user-images.githubusercontent.com/55869634/78876517-7394e700-7a1d-11ea-9942-57c843aa0d80.png)
![image](https://user-images.githubusercontent.com/55869634/78876796-df774f80-7a1d-11ea-9a12-839779032fa8.png)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - TeknoParrotUI version 1.0.0.319
 - TeknoParrotCore Version 1.0.0.139 and 1.0.0.138 (updated while i was trying to get it working)

**Additional context**
i tried before using only segatools and minime, but didn't work, had the same problem, wont launch.
i instead followed a youtube tutorial to use teknoparrot, and use the same game dump, but i deleted the modified dump and extracted it again ( the SDDF_1.31.00 folder)

**Comment by nzgamer41** [comment]
I'm not sure what causes this, will look into further although I did notice you were able to get past this issue on Discord.
