### ISSUE TITLE
Error 8114 :(

### ISSUE THREAD

**Issue by defre1976** [nzgamer41/SegaToolsTP#5]
hi , 

Yesterday i tried all afternoon to get initial d zero to work but without succes . I am always getting Error 8114 . 

New install of teknoparrot , fully updated . 
I point out InitialD0_DX11_Nu.exe in teknoparrot . 
I put my ip adress ( cmd=> ipconfig ) ivp4
IPv4 Address. . . . . . . . . . . : 192.168.0.115
Subnet Mask . . . . . . . . . . . : 255.255.255.0

When i don't put my ip adress and start the game i have the initalizing , then error 8114 
![initial 1](https://user-images.githubusercontent.com/60584123/79247276-99d1e100-7e7a-11ea-9f94-06b83eaaeeb2.png)

When i put my ip adress i have immediataly Error 8114 , i don't even see the initalizing logo . 

This i what i get 

Microsoft Windows [Version 10.0.18362.720]
(c) 2019 Microsoft Corporation. All rights reserved.

D:\Hyperspin Rocketlauncher\Hyperspin\Emulators\TeknoParrot IDZero\SegaTools\minime>start.bat
--- Begin idz_pre_startup ---
--- Begin idz_pre_startup ---
Vfs: WARNING: OPTION path not specified in INI file
---  End  idz_pre_startup ---
amdaemonExe Ver.2425 Build:Mar 29 2018 17:23:39

SetupAPI: Interface {741b5fca-...} -> Device node $sram
Vfs: WARNING: OPTION path not specified in INI file
SRAM: Open device
SRAM: Get geometry
SetupAPI: Interface {b7970f0c-...} -> Device node $eeprom
EEPROM: Open device
EEPROM: Get geometry
SetupAPI: Interface {279a9f67-...} -> Device node $ds
DS: Open device
DS: Get geometry
DS: Setup IOCTL
SetupAPI: Interface {e9a26688-...} -> Device node $gpio
GPIO: Open device
GPIO: Describe GPIO ports
Process state: setup Game Mode
Security: Opened handle
DS: Read sector 00000000
---  End  idz_pre_startup ---
Security: nusec_ioctl_get_nvram_geometry
Security: nusec_ioctl_get_nearfull
Hwmon: Opened device
AmVideo: amDllVideoOpen)
AmVideo: amDllVideoSetResolution
AmVideo: amDllVideoClose)
Netenv: GetAdaptersInfo: Virtualized LAN configuration:
Netenv: Interface IP :   192.168.  0. 11
Netenv: Router IP    :   192.168.  0.254
Netenv: MAC Address  : 
Netenv: GetAdaptersInfo: Virtualized LAN configuration:
Netenv: Interface IP :   192.168.  0. 11
Netenv: Router IP    :   192.168.  0.254
Netenv: MAC Address  : 
Netenv: GetAdaptersInfo: Virtualized LAN configuration:
Netenv: Interface IP :   192.168.  0. 11
Netenv: Router IP    :   192.168.  0.254
Netenv: MAC Address  : 
SetupAPI: Interface {db6bbb45-...} -> Device node $jvs
JVS Port: Open device
JVS I/O: Starting Initial D Zero backend DLL
TeknoParrot SegaTools Support by nzgamer41
Using Shift Up and Down!
Using TeknoParrot Input Support
JVS Port: Port startup (?)
EEPROM: Read off 1f0 len 30
EEPROM: Read off 90 len b0
EEPROM: Read off 40 len 50
JVS I/O: Reset (param d9)
  app:switchboard HOST_EXT: 127.0.0.1 (Service host name sent to clients) +0ms
  app:switchboard HOST_INT: 0.0.0.0 (Bind address) +2ms
  app:switchboard Using default host names, change them from the .env file if necessary. +2ms
Startup OK
events.js:287
      throw er; // Unhandled 'error' event
      ^

Error: listen EACCES: permission denied 0.0.0.0:80
    at Server.setupListenHandle [as _listen2] (net.js:1296:21)
    at listenInCluster (net.js:1361:12)
    at doListen (net.js:1500:7)
    at processTicksAndRejections (internal/process/task_queues.js:85:21)
Emitted 'error' event on Server instance at:
    at emitErrorNT (net.js:1340:8)
    at processTicksAndRejections (internal/process/task_queues.js:84:21) {
  code: 'EACCES',
  errno: 'EACCES',
  syscall: 'listen',
  address: '0.0.0.0',
  port: 80
}

Press any key to continue . . . Error 0
NFC Assembly: Starting backend DLL
NFC 00: Reset
JVS I/O: Reset (param d9)
JVS Port: Sense line 2.5 V (address unassigned)
JVS I/O: Assign addr 01 sense 0
JVS Port: Sense line 0.0 V (address assigned)
JVS I/O: Get features
JVS I/O: Get command format version
JVS I/O: Get JVS version
JVS I/O: Get communication version
JVS I/O: Read ID
Netenv: GetBestRoute ip4 0 -> ip4 0
Process state: Advertise
Clock: Returning JST timezone
Security: nusec_ioctl_get_billing_pubkey
>>> 00000001408387C1:0/1024
<<< 00000001408387C1:162/1024
Security: nusec_ioctl_get_play_limit
Netenv: GetBestRoute ip4 0 -> ip4 c0a8000b
Netenv: GetBestRoute ip4 0 -> ip4 c0a8000b
Security: nusec_ioctl_get_nearfull
start LAN install - server.
Netenv: Virtualized ICMP Ping to ip4 c0a800fe
Security: nusec_ioctl_get_play_count
Netenv: Virtualized ICMP Ping to ip4 c0a800fe
Netenv: Virtualized ICMP Ping to ip4 c0a800fe
Security: nusec_ioctl_put_trace_log_data
    00000000: 01 14 04 0e 10 10 06 50 6f 77 65 72 20 6f 6e 20 .......Power on
    00000010: 41 36 39 45 30 31 41 38 38 38 38 20 53 44 44 46 A69E01A8888 SDDF
    00000020: 20 31 2e 33 31 20 20 20 41 36 39 45 01 41 88 88  1.31   A69E.A..
    00000030: 18 05 00 00 00 00 00 00 00 00 00 00             ............

    H: 1 T: 0
Security: nusec_ioctl_put_trace_log_data
    00000000: 02 14 04 0e 10 10 06 00 00 00 01 01 00 01 01 01 ................
    00000010: 01 02 03 04 05 06 18 05 41 36 39 45 01 41 88 88 ........A69E.A..
    00000020: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 ................
    00000030: 00 00 00 00 00 00 00 00 00 00 00 00             ............

    H: 2 T: 0
Clock: Returning JST timezone
EEPROM: Read off 1000 len 80
Netenv: GetAdaptersInfo: Virtualized LAN configuration:
Netenv: Interface IP :   192.168.  0. 11
Netenv: Router IP    :   192.168.  0.254
Netenv: MAC Address  : 01:02:03:04:05:06
Netenv: Virtualized ICMP Ping to ip4 c0a80073
Netenv: Virtualized ICMP Ping to ip4 c0a80073
Netenv: Virtualized ICMP Ping to ip4 c0a80073
start NET deliver.
App Image    - Download Status: 200
Option Image - Download Status: 200
Security: nusec_ioctl_get_nvram_available: used=2 avail=7152
Error 8114
ZInput: Blocking built-in DirectInput support
ZInput: hook_CreateDevice
ZInput: hook_SetDataFormat
ZInput: hook_SetCooperativeLevel
ZInput: hook_CreateDevice
ZInput: hook_SetDataFormat
ZInput: hook_SetCooperativeLevel
ZInput: hook_EnumDevices

What i have done , remove segatools folder , restart teknoparrot , go to minime and start the bat file . It download things and so , i restart teknoparrot and still the same error . 

Could you please help 

thank you

**Comment by nzgamer41** [comment]
Do you have something else running on your system using Port 80? like a web server? minime is showing it can't use port 80 on your system, meaning something else is running using that port.

**Comment by defre1976** [comment]
no , not that i know . Utorrent start up automatic , also Rewasd is running . I mean its in my tray. I don't know anything else .

**Comment by defre1976** [comment]
i just checked everything , i don't have any webserver . Utorrrent close , rewasd close . Don't know what else it could be that use port 80?

**Comment by defre1976** [comment]
i downloaded Cports , and i see 2 lines System that is using port 80 ? I can also not close it . 
Windows update is going i saw . Could this be the problem . So everythime windows would be checking for updates i can not play intial D zero ?
I let you know when all the updates are done .

**Comment by defre1976** [comment]
i found it , answer here https://stackoverflow.com/questions/1430141/port-80-is-being-used-by-system-pid-4-what-is-that

Task manager => services => W3SVC ( world Wide web publishing service ) 
I stopped this and now it works.
Tottaly don't know what this service is , but i think it will start again when i restart my pc .

**Comment by nzgamer41** [comment]
I will close this, but thank you for explaining how you fixed it, it will help others with this issue.
